github action to copy read me to arc-docs
sourcefuse/terraform-aws-ref-arch-db pull request #32
Opened 2023-03-23 06:32 UTC by saurabhjindal-SF

2023-03-24 17:41 UTC, jamescrowley321 requested changes

2023-03-24 17:41 UTC, jamescrowley321 commented on .github/workflows/update-docs.yml
> +          user_email: 'saurabh.jindal@gmail.com'
Can this be updated to a service account or the author of the PR's username and email?

2023-03-25 21:53 UTC, mayank0202 approved these changes

2023-03-26 15:42 UTC, jamescrowley321 approved these changes

2023-03-26 15:42 UTC, merged